FROM almalinux:9   
RUN dnf install nginx -y
RUN rm -rf /usr/share/nginx/html/index.html
#this instruction runs when someone uses this image as a base image in their Dockerfile. It will copy the index.html file from the build context to the specified location in the container when the ONBUILD instruction is triggered.
ONBUILD COPY index.html /usr/share/nginx/html/index.html
CMD ["nginx", "-g", "daemon off;"]